name: Build Desktop App

on:
  push:
    branches: [ main, cicd ]
  pull_request:
    branches: [ main,cicd ]

jobs:
  build:
    strategy:
      matrix:
        # Define the operating systems to build on
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # --- START OF FIX ---
      - name: Build with Gradle
        # This step now runs the specific packaging task for each OS.
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat packageMsi
          elif [ "$RUNNER_OS" == "Linux" ]; then
            ./gradlew packageDeb
          elif [ "$RUNNER_OS" == "macOS" ]; then
            ./gradlew packageDmg
          fi
      # --- END OF FIX ---

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ModernADB-${{ matrix.os }}
          # This path uses wildcards to find the correct output file on each runner.
          path: |
            composeApp/build/compose/binaries/main/**/*.msi
            composeApp/build/compose/binaries/main/**/*.dmg
            composeApp/build/compose/binaries/main/**/*.deb
